"""Initial migration

Revision ID: c4c0bff3b909
Revises: 
Create Date: 2024-12-24 17:22:52.718099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4c0bff3b909'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('station',
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('parameter',
    sa.Column('station', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('tavg', sa.Float(), nullable=True),
    sa.Column('tmin', sa.Float(), nullable=True),
    sa.Column('tmax', sa.Float(), nullable=True),
    sa.Column('havg', sa.Integer(), nullable=True),
    sa.Column('hmin', sa.Integer(), nullable=True),
    sa.Column('etavg', sa.Float(), nullable=True),
    sa.Column('etmin', sa.Float(), nullable=True),
    sa.Column('etmax', sa.Float(), nullable=True),
    sa.Column('windavg', sa.Float(), nullable=True),
    sa.Column('windimp', sa.Float(), nullable=True),
    sa.Column('visavg', sa.Float(), nullable=True),
    sa.Column('pavg', sa.Float(), nullable=True),
    sa.Column('pmin', sa.Float(), nullable=True),
    sa.Column('pmax', sa.Float(), nullable=True),
    sa.Column('poavg', sa.Float(), nullable=True),
    sa.Column('pomin', sa.Float(), nullable=True),
    sa.Column('pomax', sa.Float(), nullable=True),
    sa.Column('night', sa.Float(), nullable=True),
    sa.Column('day', sa.Float(), nullable=True),
    sa.Column('summary', sa.Float(), nullable=True),
    sa.Column('rain', sa.Float(), nullable=True),
    sa.Column('snow', sa.Float(), nullable=True),
    sa.Column('fog', sa.Float(), nullable=True),
    sa.Column('duststorm', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['station'], ['station.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parameter')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('station')
    # ### end Alembic commands ###
